---
# Global Variables Configuration
# Author: GCG AAP SSA Team + v3.01 Date 20260217

# Administrator user configuration
admin_user: admin
admin_password: redhat

# Firewall ports configuration
firewall_ports:
  - 50051
  - 53
  - 80
  - 443
  - 5432
  - 6379
  - 27199
  - 9000
  - 9001
  - 9002
  - 9003

# NTP servers configuration
ntp_servers:
  - ntp.aliyun.com
  - ntp1.aliyun.com
  - ntp2.aliyun.com

# Network configuration
network:
  allowed_subnets:
    - 10.66.0.0/16
    - 192.168.0.0/16

# Template server configuration
template_server:
  host: 10.66.208.237
  hosts_file: /etc/hosts

# System optimization parameters
system_limits:
  - "prometheus soft nofile 65536"
  - "prometheus hard nofile 65536"
  - "* soft nofile 65536"
  - "* hard nofile 65536"

sysctl_params:
  net.core.somaxconn: 65535
  net.ipv4.tcp_max_syn_backlog: 65535
  vm.max_map_count: 262144

# SELinux configuration
selinux:
  state: permissive
  policy: targeted

# Backup configuration
backup:
  enabled: true
  suffix: ".backup.$(date +%Y%m%d_%H%M%S)"

